name: Build DLL x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          choco install visualstudio2026buildtools `
            --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" `
            -y
          choco install cmake -y

      - name: Build Solution
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2026\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86
          msbuild "Source\D3D9 Hook ImGui\D3D9 Hook ImGui.sln" /p:Configuration=Release /p:Platform=Win32

      - name: Upload artifact/s
        uses: actions/upload-artifact@v6
        with:
          name: DLL
          path: Source/D3D9 Hook ImGui/Release/D3D9 Hook ImGui.dll
