name: Build DLL x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install CMake
        shell: pwsh
        run: choco install directx-sdk cmake -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Check Solution File
        shell: cmd
        run: dir "Source\D3D9 Hook ImGui"

      - name: Build Solution x86
        shell: cmd
        run: |
          REM Build using MSBuild for Win32 (x86)
          msbuild "Source\D3D9 Hook ImGui.sln" ^
            /p:Configuration=Release ^
            /p:Platform=x86 ^
            /p:IncludePath="%DXSDK_DIR%Include;%IncludePath%" ^
            /p:LibraryPath="%DXSDK_DIR%Lib\x86;%LibraryPath%" ^
            /m

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v6
        with:
          name: DLL
          path: "Source/D3D9 Hook ImGui/Release/D3D9 Hook ImGui.dll"
