name: Build DLL x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Chocolatey Packages
        shell: pwsh
        run: |
          choco install cmake -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        shell: cmd
        run: |
          REM Use preinstalled Visual Studio 2022 environment for x86
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86
          msbuild "Source\D3D9 Hook ImGui\D3D9 Hook ImGui.sln" /p:Configuration=Release /p:Platform=Win32

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v6
        with:
          name: DLL
          path: Source/D3D9 Hook ImGui/Release/D3D9 Hook ImGui.dll
